numero_usuario = int(input("Digite um número para ver sua tabuada: "))

print("-"*27)
print(f"{numero_usuario} x {1:2} = {numero_usuario * 1}")
print(f"{numero_usuario} x {2:2} = {numero_usuario * 2}")
print(f"{numero_usuario} x {3:2} = {numero_usuario * 3}")
print(f"{numero_usuario} x {4:2} = {numero_usuario * 4}")
print(f"{numero_usuario} x {5:2} = {numero_usuario * 5}")
print(f"{numero_usuario} x {6:2} = {numero_usuario * 6}")
print(f"{numero_usuario} x {7:2} = {numero_usuario * 7}")
print(f"{numero_usuario} x {8:2} = {numero_usuario * 8}")
print(f"{numero_usuario} x {9:2} = {numero_usuario * 9}")
print(f"{numero_usuario} x {10} = {numero_usuario * 10}")
print("-"*27)
